theme: jekyll-theme-minimal

title: An alarm cape for the Beaglebone Black
description: The bbbalarm cape enhance the Beaglebone Black by adding coupled and decoupled inputs, that can be used to supervise an air condition or read out a presence detector.
logo: https://github.com/eurovibes/bbbalarm/raw/master/images/bbbalarm.png
show_downloads: true

github:
  zip_url: downloads/fabrication.zip
  tar_url: downloads/fabrication.tar.gz
